### PR TITLE
Fix non-combat creature summons from relevant JC Figurine trinket uses

### PR DESCRIPTION
**Pull request by MantisLord**
This applies to TBC-DB only. It seems to be working in UDB.

These creatures are summoned by using Figurine trinkets made by Jewelcrafting.
They are supposed to just be cosmetic critters and not aggro or attack anything.

Closes:
http://jira.vengeancewow.com/projects/TBC/issues/TBC-1755

### CODE REVIEW

**Comment by Phatcat** [comment]
Just need to assign them extra flag no melee or unit flag passive.

**Comment by killerwife** [comment]
Instead of 768 prolly 514 is more appropriate.

**Comment by MantisLord** [comment]
UDB has flags_extra 2 (CREATURE_EXTRA_FLAG_CIVILIAN) for each of these and no Unit/NPC flags - it seems to work fine like this.

TBC does not exhibit the same behavior. With no Unit flags set and just ExtraFlags 2, creatures still draw aggro.

UnitFlag 514 also fixes the issue. (UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_PASSIVE)

**Comment by Phatcat** [comment]
because the petai is built around unit flag passive and extra flag no melee. i have not included extra flag civillian anywhere in it cause it frankly doesnt have anything to do with pets.

**Comment by killerwife** [comment]
Alright, so if I set passive/non_attackable and NO_MELEE it should work then.

**Comment by Phatcat** [comment]
No reason to set no melee if you set passive: passive makes sure it never fights anything and no melee just makes sure it doesnt melee. Theres no reason to care about melee if you remove attacking from it.

Yes, probably need 'non attackable' to make sure others cant attack it either.

**Comment by Phatcat** [comment]
Probably want to take a look at other critters and see what flags are set for them since they work pretty well for the most part.

**Comment by killerwife** [comment]
They have UnitFlags 514 afaik.

**Pull request closed without merging**
