### PR TITLE
Removed NPC damage and armor modifiers edits. 

### PR DESCRIPTION
**Pull request by snaiperskaya96**
NPCs cause no more than 1 melee damage with them setted on 0

### CODE REVIEW

**Comment by snaiperskaya96** [comment]
**In my opinion** it makes no sense to set them to 0. Even if final products are wrong at least it is still playable.
A new user like me would spend many time to find what's wrong with melee damage.
You're currently swapping something wrong with something worst.

**Comment by BlackMetalz** [comment]
hmmm, i tested without change remove npc damage, my character level 1 still get hit not only like 1 dmg. So it could be wrong!

**Comment by BlackMetalz** [comment]
comment on those set to 0 is correct way :pager:

**Comment by ulfgebhardt** [comment]
Was this merged? This renders the default Database useless, its not in the interest of the community to not merge this. I completely agree with @snaiperskaya96

**Pull request closed without merging**
