### PR TITLE
Script quests 10806, 10742 (Showdown)

### PR DESCRIPTION
**Pull request by MantisLord**
Nothing happens currently in both UDB and TBC-DB when you use item at Altar of Goc. 
This PR works for both.

TODO:
- [x] ~~Need better solution for preventing multiple Goc summons.~~ (thanks @killerwife)
- [x] ~~Add Baron Sablemane transformation event AI~~

Sources:
https://www.youtube.com/watch?v=Apunkv4js3I (Horde)
https://www.youtube.com/watch?v=hroPV08gszo (Horde)
https://www.youtube.com/watch?v=_e2Z-gQmz_o (Alliance)

Closes:
http://jira.vengeancewow.com/browse/TBC-1190

### CODE REVIEW

**Comment by killerwife** [comment]
Alright, so :)

https://gist.github.com/killerwife/1e880b82462bc38d900ab880808e4982

I added a check for multiple GOC spawns. Also added two comments that are needed to complete the ALLIANCE version. Please add that, and then I will accept this script :)

Good job anyway.

**Comment by killerwife** [comment]
Alright, I noticed two things. 1st turns out he is supposed to transform at 15% of GOC not 30% of baron. Also you have a typo there. (39225 instead of 39255) I will finish it from this point.

**Comment by MantisLord** [comment]
Thank you for your feedback. I know you said you would finish, but I couldn't help myself.
You were right about the incorrect spell ID, good catch. Phases needed to be adjusted slightly so that he has time to cast.

**Comment by killerwife** [comment]
Sheesh, I already pushed it but I will add the adjustments to our repo.

**Comment by killerwife** [comment]
oh and btw, you can have two events at 15%

**Comment by killerwife** [comment]
And one more thing, use double ' instead of ". " is not standard amongst SQL standards, therefore if you have an apostrophe in a text just use double apostrophe.

**Pull request closed without merging**
